### PR TITLE
Update to gatsby 4 

### PR DESCRIPTION
**Pull request by thinkybeast**
Hi! In case you didn’t know, Gatsby is planning its next major version for Q4 of this year! In preparation, the Gatsby team is reaching out to maintainers for our most popular Starters to help make the upgrade to Gatsby 4 as smooth as possible.

This PR updates your Gatsby Starter to the beta version of this next release, as well as some related plugins. It also migrates from Gatsby Image to gatsby-plugin-image. 

It’s just in draft form for now, since the 4.0.0 version of Gatsby isn’t quite ready for release yet. We’re mainly testing updating Gatsby and the other official plugins to ensure that the Starter builds without errors.

You may see some warnings from packages that list `gatsby: ^3.0.0` as a peer dependency.  Don’t worry, we’ll come back and fix those before we take this PR out of draft mode when it’s ready to be merged.

* Note: Gatsby 4 requires Node v14. This is a change from Gatsby 3, which worked with Node v12.13 or newer.

Once version 4.0.0 is ready, we'll come back to update the dependencies and convert this draft to a PR for review. Until then, no action is required on your end. If you have any questions / concerns, let us know in the comments. 

Thanks again for all your work as a Gatsby maintainer. We’re so grateful to have you as part of our community. 💜

For more information on what’s coming with Gatsby v4, check out the [GitHub Discussion](https://github.com/gatsbyjs/gatsby/discussions/32860).

### CODE REVIEW

**Comment by stefanoverna** [comment]
Thanks @thinkybeast!

**Comment by rmatambo8** [comment]
From GatsbyJS,

Hey @stefanoverna! Gatsby is almost ready for the stable release of version 4.0.0. 

**We are planning on having a major launch day this month and we would like to merge all of these changes, we would like to feature your starter from day 1 of Gatsby 4 GA. Would you be up for merging on the launch day?**

As always, we're glad that DatoCMS could be an awesome Gatsby partner. We’re so grateful to have you as part of our community. 💜

Feel free to jump into the discussion on quality starters for Gatsby v4 in the [GitHub Discussion](https://github.com/gatsbyjs/gatsby/discussions/33346)

**Comment by stefanoverna** [comment]
Sure thing @rmatambo8! Currently the build is failing though:

```
6:34:25 PM: error gatsby@4.0.0-zz-next.2: The engine "node" is incompatible with this module. Expected version ">=14.15.0". Got "12.18.0"
```

could you please try to add a .node-version or .nvmrc file to the base directory in the repository?

**Comment by thinkybeast** [comment]
@stefanoverna We're GA today! Just updated the dependencies, added an .nvmrc, and resolved some conflicts with changes since I originally forked the branch.  

Take a look when you have a chance, and feel free to merge if everything looks good :)

**Comment by stefanoverna** [comment]
Thanks @thinkybeast.. but it's still failing :( https://app.netlify.com/sites/datocms-gatsby-blog-demo/deploys/61719c4b75e3a700078ca704

**Comment by thinkybeast** [comment]
@stefanoverna Fixed the install errors, but seems like we're failing on data being null while rendering. What project is the Netlify build sourcing from? I cloned the gatsby-blog-demo data template for local testing.

**Comment by stefanoverna** [comment]
Hey @thinkybeast! First of all, please use gatsby-source-datocms@3.0.0 — which should be fully v4 compliant.

I've tried to run this project locally (apiToken: 7fd4c772c9d2a6cb2b8f0122e59f50) and on development it works, while during a build it doesn't. 

I've tried to debug this, and it is very strange. I don't know if it's something related to some changes you made to Gatsby v4 but:

First of all, you can see the "loading DatoCMS schema" line is present twice in Netlify logs.. which it means that that our `createSchemaCustomization` hook is called twice. Is that normal?

Then it gets stranger.

Our plugin uses some memoized `Loader` instances, so that the different hooks can all rely to content that has already been downloaded in previous steps of the process.

Here is the memoization mechanism:

https://github.com/datocms/gatsby-source-datocms/blob/master/src/utils.js#L64

And here you can see the different hooks that get their `Loader` instance:

https://github.com/datocms/gatsby-source-datocms/blob/master/src/hooks/createSchemaCustomization/index.js#L38

https://github.com/datocms/gatsby-source-datocms/blob/master/src/hooks/sourceNodes/index.js#L75-L82

Now. Here's what happens:

The `loader` gets instanciated in the first `createSchemaCustomization` hook:

```
12:03:34 AM: success onPreBootstrap - 0.450s
12:03:35 AM: success loading DatoCMS schema - 0.758s
12:03:35 AM: success createSchemaCustomization - 0.791s
```

The `sourceNodes` hook uses the `loader` created in the `createSchemaCustomization` hook:

```
12:03:39 AM: success loading DatoCMS content - 3.580s
```

But when the `createSchemaCustomization` hook gets called again here..

```
12:03:43 AM: success onPreExtractQueries - 0.000s
12:03:45 AM: success loading DatoCMS schema - 1.984s
12:03:48 AM: success extract queries from components - 5.450s
```

...for some reason it creates a new loader, because the `loaders` cache is completely empty:

https://github.com/datocms/gatsby-source-datocms/blob/master/src/utils.js#L12

So that's the reason why some data is missing and the build fails.

Now. The only reason I can think that empties the `loaders` local variable is because Gatsby is spinning up a different Node process. Is that the case? How can we fix this issue on our source plugin? I suppose we're not the only CMS having to rework the logic of their source plugin.

**Comment by DanielSLew** [comment]
> Now. The only reason I can think that empties the `loaders` local variable is because Gatsby is spinning up a different Node process. Is that the case? How can we fix this issue on our source plugin? I suppose we're not the only CMS having to rework the logic of their source plugin.

@stefanoverna with Gatsby v4 we spin up a different node process for the different APIs, which is why the APIs can no longer rely on global state that is set in a separate node process. I believe we can persist to cache and then load the loader in `onPluginInit`, `onPluginInit` is a new gatsby lifecycle API that is called everytime a new node process is created, so we can ensure that this process has whatever global state we need.

**Comment by stefanoverna** [comment]
Thanks @DanielSLew, can you point us to a source plugin that is using the new hook in such fashion please? 🙏

**Comment by stefanoverna** [comment]
Alright, @thinkybeast / @DanielSLew v3.0.5 of gatsby-source-datocms plugin should solve the issue!

**Comment by stefanoverna** [comment]
Thanks for your help!

**Pull request merged**
